version: '3'

services:
  #######################  mariadb  ########################
  cudgx-mysql:
    container_name: mariadb-server
    image: yobasystems/alpine-mariadb:10.5.11
    network_mode: "host"
    environment:
      MYSQL_ROOT_PASSWORD: mtQ8chN2
      MYSQL_DATABASE: cudgx
      MYSQL_USER: gf
      MYSQL_PASSWORD: db@galaxy-future.com
    ports:
      - 3336:3306
    volumes:
      - ./init/mysql:/docker-entrypoint-initdb.d/
    restart: always
  #######################  kafka  ########################
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - /etc/localtime:/etc/localtime

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    links:
      - zookeeper
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_PORT=9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  #######################  clickhouse  ########################
  clickhouse-server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./init/clickhouse/quickstart:/docker-entrypoint-initdb.d/
#  clickhouse-client:
#    image: yandex/clickhouse-client
#    command: [ '--host', 'server' ]

  #######################  cudgx 1.0  ########################
  api:
    container_name: gf-cudgx-api
    image: cudgx_api:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    depends_on:
      - cudgx-mysql
      - kafka
      - clickhouse-server

  gateway:
    container_name: gf-cudgx-gateway
    image: cudgx_gateway:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: ./docker/gateway.Dockerfile
    depends_on:
      - api

  consumer:
    container_name: gf-cudgx-consumer
    image: cudgx_consumer:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: ./docker/consumer.Dockerfile
    depends_on:
      - gateway

  sample-pi:
    container_name: gf-cudgx-sample-pi
    image: cudgx_sample_pi:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: ./docker/pi.Dockerfile
    depends_on:
      - api
      - gateway
      - consumer

  sample-benchmark:
    container_name: gf-cudgx-sample-benchmark
    image: cudgx_sample_benchmark:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: ./docker/benchmark.Dockerfile
    depends_on:
      - api
      - gateway
      - consumer
