apiVersion: v1
kind: ConfigMap
metadata:
  name: cudgx-api-prod-config
data:
  api.json: '
{
  "param": {
    "samples_query_count": 60,
    "predict_minimal_count": 50,
    "minimal_skip_factor": 0.1,
    "maximal_skip_factor": 0.1
  },
  "database": {
    "dsn": "root:db@galaxy-future.com@tcp(172.16.16.169:3306)/cudgx?charset=utf8mb4&parseTime=True&loc=Local"
  },
  "xclient": {
    "bridgx_server_address": "http://iapi.galaxy-future.com/bridgx",
    "schedulx_server_address": "http://iapi.galaxy-future.com/schedulx"
  },
  "victoria_metrics": {
      "reader": {
        "vm_url": "http://172.16.16.223:8481/select/0/prometheus"
      }
  }
}
  '

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cudgx-api-prod
  labels:
    app: cudgx-api-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cudgx-api-prod
  template:
    metadata:
      labels:
        app: cudgx-api-prod
    spec:
      containers:
        - name: api
          image: 172.16.16.172:12380/cudgx/api:v0.7
          imagePullPolicy: Always
          ports:
            - containerPort: 19003
          env:
            - name: GIN_MODE
              value: release
          volumeMounts:
            - name: configure
              mountPath: /home/cudgx/conf

      volumes:
        - name: configure
          configMap:
            name: cudgx-api-prod-config

---

apiVersion: v1
kind: Service
metadata:
  name: cudgx-api-prod
spec:
  selector:
    app: cudgx-api-prod
  type: NodePort
  ports:
    - protocol: TCP
      port: 19003