apiVersion: v1
kind: ConfigMap
metadata:
  name: cudgx-gateway-config
  namespace: cudgx
data:
  gateway.json: '
  {
  "monitoring_route": {
    "default": {
      "brokers": ["172.16.16.180:9092"],
      "topic": "monitoring_metrics"
    },
    "entries": [
      {
        "service_prefix": "gf",
        "brokers": ["172.16.16.180:9092"],
        "topic": "monitoring_metrics_gf"
      }
    ]
  },
  "streaming_route": {
    "default": {
      "brokers": ["172.16.16.180:9092"],
      "topic": "streaming_metrics"
    },
    "entries": [
      {
        "service_prefix": "gf",
        "brokers": ["172.16.16.180:9092"],
        "topic": "streaming_metrics_gf"
      }
    ]
  },

  "producer": {
    "MaxMessageBytes": 1000000,
    "RequiredAcks": "WaitForLocal",
    "Timeout": "10s",
    "Compression": "none",
    "CompressionLevel": -1000,
    "Return": {
      "Successes": false,
      "Errors": true
    },
    "Flush": {
      "Bytes": 1024,
      "Messages": 0,
      "Frequency": "1s",
      "MaxMessages": 0
    },
    "Retry": {
      "Max": 3,
      "Backoff": "100ms"
    }
  },
  "database": {
    "dsn": "root:db@galaxy-future.com@tcp(172.16.16.169:3306)/cudgx?charset=utf8mb4&parseTime=True&loc=Local",
    "refresh_seconds": 5
  }
}
  '

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cudgx-gateway
  labels:
    app: cudgx-gateway
  namespace: cudgx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cudgx-gateway
  template:
    metadata:
      labels:
        app: cudgx-gateway
    spec:
      containers:
        - name: gateway
          image: 172.16.16.172:12380/cudgx/gateway:v0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 19000
          env:
            - name: GIN_MODE
              value: release
          volumeMounts:
            - name: configure
              mountPath: /home/cudgx/conf

      volumes:
        - name: configure
          configMap:
            name: cudgx-gateway-config

---

apiVersion: v1
kind: Service
metadata:
  name: cudgx-gateway
  namespace: cudgx
spec:
  selector:
    app: cudgx-gateway
  type: NodePort
  ports:
    - protocol: TCP
      port: 19000